-- Applied live: phase4_b1_team_authority_foundation
-- JANTA BOL Phase 4 B1 — Team / Authority Extension
-- Preserve auth.users -> user_roles -> reporters -> Live.
-- team_accounts stores lifecycle metadata only; user_roles remains effective authorization.

alter table public.reporters
  add column if not exists public_name_enabled boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.team_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete restrict,
  reporter_id uuid unique references public.reporters(id) on delete restrict,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 120),
  contact text,
  invite_email text,
  assigned_role public.app_role not null default 'reporter'::public.app_role
    check (assigned_role <> 'owner'::public.app_role),
  status text not null default 'pending'
    check (status in ('pending','active','suspended','departed')),
  invited_at timestamptz not null default now(),
  activated_at timestamptz,
  suspended_at timestamptz,
  departed_at timestamptz,
  last_reactivated_at timestamptz,
  status_reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists team_accounts_status_idx
  on public.team_accounts(status, updated_at desc);
create index if not exists team_accounts_role_idx
  on public.team_accounts(assigned_role, status);

create table if not exists public.team_account_history (
  id bigint generated by default as identity primary key,
  team_account_id uuid not null references public.team_accounts(id) on delete restrict,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 1 and 100),
  old_status text,
  new_status text,
  old_role public.app_role,
  new_role public.app_role,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists team_account_history_account_idx
  on public.team_account_history(team_account_id, created_at desc);

alter table public.team_accounts enable row level security;
alter table public.team_account_history enable row level security;

drop policy if exists team_accounts_owner_read on public.team_accounts;
create policy team_accounts_owner_read on public.team_accounts
for select to authenticated using (private.current_owner_aal2());

drop policy if exists team_accounts_self_read on public.team_accounts;
create policy team_accounts_self_read on public.team_accounts
for select to authenticated
using (user_id=(select auth.uid()) and private.current_session_active());

drop policy if exists team_history_owner_read on public.team_account_history;
create policy team_history_owner_read on public.team_account_history
for select to authenticated using (private.current_owner_aal2());

revoke all on table public.team_accounts from anon,authenticated;
revoke all on table public.team_account_history from anon,authenticated;
grant select on table public.team_accounts to authenticated;
grant select on table public.team_account_history to authenticated;

insert into public.team_accounts(
  user_id,reporter_id,display_name,contact,assigned_role,status,
  invited_at,activated_at,created_at,updated_at
)
select
  ur.user_id,r.id,
  coalesce(nullif(btrim(r.name),''),nullif(split_part(u.email,'@',1),''),'Team Member'),
  r.contact,ur.role,'active',
  coalesce(r.created_at,ur.created_at,now()),
  coalesce(ur.created_at,r.created_at,now()),
  coalesce(r.created_at,ur.created_at,now()),now()
from public.user_roles ur
join auth.users u on u.id=ur.user_id
left join public.reporters r on r.user_id=ur.user_id
where ur.role<>'owner'::public.app_role
on conflict(user_id) do nothing;

create or replace function private.current_app_role()
returns public.app_role language sql stable security definer
set search_path='public','private','auth','pg_temp'
as $$
  select ur.role
  from public.user_roles ur
  where ur.user_id=auth.uid()
    and (
      ur.role='owner'::public.app_role
      or exists(
        select 1 from public.team_accounts ta
        where ta.user_id=ur.user_id and ta.status='active'
      )
    )
  limit 1;
$$;

create or replace function private.jb_team_history_internal(
  p_team_account_id uuid,p_actor_user_id uuid,p_action text,
  p_old_status text,p_new_status text,p_old_role public.app_role,
  p_new_role public.app_role,p_reason text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint language plpgsql security definer set search_path=''
as $$
declare v_id bigint;
begin
  insert into public.team_account_history(
    team_account_id,actor_user_id,action,old_status,new_status,
    old_role,new_role,reason,metadata
  ) values(
    p_team_account_id,p_actor_user_id,left(btrim(p_action),100),
    p_old_status,p_new_status,p_old_role,p_new_role,
    nullif(left(btrim(coalesce(p_reason,'')),500),''),
    coalesce(p_metadata,'{}'::jsonb)
  ) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.jb_team_create_pending_internal(
  p_owner_user_id uuid,p_user_id uuid,p_display_name text,p_contact text,
  p_role public.app_role,p_invite_email text default null
)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare
  v_account public.team_accounts%rowtype;
  v_name text:=left(btrim(coalesce(p_display_name,'')),120);
  v_contact text:=nullif(left(btrim(coalesce(p_contact,'')),240),'');
  v_email text:=nullif(lower(left(btrim(coalesce(p_invite_email,'')),320)),'');
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  if v_name='' then raise exception 'DISPLAY_NAME_REQUIRED'; end if;
  if p_role is null or p_role='owner'::public.app_role then raise exception 'INVALID_TEAM_ROLE'; end if;
  if p_user_id is not null and exists(select 1 from public.team_accounts where user_id=p_user_id)
    then raise exception 'TEAM_USER_ALREADY_EXISTS'; end if;

  insert into public.team_accounts(
    user_id,display_name,contact,invite_email,assigned_role,status,created_by
  ) values(p_user_id,v_name,v_contact,v_email,p_role,'pending',p_owner_user_id)
  returning * into v_account;

  perform private.jb_team_history_internal(
    v_account.id,p_owner_user_id,'team_invited',null,'pending',null,p_role,null,
    jsonb_build_object('user_linked',p_user_id is not null)
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_invited','team_account',v_account.id::text,
         jsonb_build_object('assigned_role',p_role::text,'user_linked',p_user_id is not null));

  return jsonb_build_object(
    'id',v_account.id,'user_id',v_account.user_id,'status',v_account.status,
    'assigned_role',v_account.assigned_role,'display_name',v_account.display_name
  );
end;
$$;

create or replace function public.jb_team_activate_internal(
  p_owner_user_id uuid,p_team_account_id uuid
)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v public.team_accounts%rowtype; v_reporter_id uuid;
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  select * into v from public.team_accounts where id=p_team_account_id for update;
  if not found then raise exception 'TEAM_ACCOUNT_NOT_FOUND'; end if;
  if v.status<>'pending' then raise exception 'TEAM_ACCOUNT_NOT_PENDING'; end if;
  if v.user_id is null then raise exception 'TEAM_AUTH_USER_REQUIRED'; end if;
  if v.assigned_role='owner'::public.app_role then raise exception 'OWNER_ROLE_RESERVED'; end if;

  insert into public.user_roles(user_id,role,created_at,updated_at)
  values(v.user_id,v.assigned_role,now(),now())
  on conflict(user_id) do update set role=excluded.role,updated_at=now();

  if v.assigned_role='reporter'::public.app_role then
    select id into v_reporter_id from public.reporters where user_id=v.user_id;
    if v_reporter_id is null then
      insert into public.reporters(
        user_id,name,contact,active,live_permission,public_name_enabled,created_at,updated_at
      ) values(v.user_id,v.display_name,v.contact,true,false,true,now(),now())
      returning id into v_reporter_id;
    else
      update public.reporters set active=true,updated_at=now() where id=v_reporter_id;
    end if;
  else
    v_reporter_id:=v.reporter_id;
    if v_reporter_id is not null then
      update public.reporters set active=false,updated_at=now() where id=v_reporter_id;
    end if;
  end if;

  update public.team_accounts
  set reporter_id=coalesce(v_reporter_id,reporter_id),status='active',
      activated_at=coalesce(activated_at,now()),suspended_at=null,
      status_reason=null,updated_at=now()
  where id=v.id returning * into v;

  perform private.jb_team_history_internal(
    v.id,p_owner_user_id,'team_activated','pending','active',
    v.assigned_role,v.assigned_role,null,'{}'::jsonb
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_activated','team_account',v.id::text,
         jsonb_build_object('assigned_role',v.assigned_role::text));
  insert into public.live_notifications(
    recipient_user_id,notification_type,priority,title,safe_message,record_type,record_id
  ) values(v.user_id,'TEAM_ACCOUNT_ACTIVATED','HIGH','JANTA BOL access activated',
           'Aapka newsroom account activate ho gaya hai.','team_account',v.id::text);
  return jsonb_build_object('id',v.id,'status',v.status,'assigned_role',v.assigned_role,'user_id',v.user_id);
end;
$$;

create or replace function public.jb_team_suspend_internal(
  p_owner_user_id uuid,p_team_account_id uuid,p_reason text
)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare
  v public.team_accounts%rowtype;
  v_reason text:=nullif(left(btrim(coalesce(p_reason,'')),500),'');
  v_sessions int:=0;
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  if v_reason is null then raise exception 'REASON_REQUIRED'; end if;
  select * into v from public.team_accounts where id=p_team_account_id for update;
  if not found then raise exception 'TEAM_ACCOUNT_NOT_FOUND'; end if;
  if v.status<>'active' then raise exception 'TEAM_ACCOUNT_NOT_ACTIVE'; end if;
  if v.user_id is null then raise exception 'TEAM_AUTH_USER_REQUIRED'; end if;

  if v.assigned_role='reporter'::public.app_role
     and exists(select 1 from public.user_roles where user_id=v.user_id and role='reporter'::public.app_role) then
    perform public.jb_live_suspend_reporter_internal(p_owner_user_id,v.user_id,v_reason);
    perform public.jb_live_revoke_reporter_capabilities_internal(p_owner_user_id,v.user_id,v_reason);
  else
    delete from auth.sessions where user_id=v.user_id;
    get diagnostics v_sessions=row_count;
  end if;
  delete from public.user_roles where user_id=v.user_id and role<>'owner'::public.app_role;
  update public.team_accounts
  set status='suspended',suspended_at=now(),status_reason=v_reason,updated_at=now()
  where id=v.id;
  perform private.jb_team_history_internal(
    v.id,p_owner_user_id,'team_suspended','active','suspended',
    v.assigned_role,v.assigned_role,v_reason,
    jsonb_build_object('non_reporter_sessions_revoked',v_sessions)
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_suspended','team_account',v.id::text,
         jsonb_build_object('reason',v_reason,'assigned_role',v.assigned_role::text));
  insert into public.live_notifications(
    recipient_user_id,notification_type,priority,title,safe_message,record_type,record_id
  ) values(v.user_id,'TEAM_ACCOUNT_SUSPENDED','CRITICAL','JANTA BOL access suspended',
           'Aapka newsroom access suspend kiya gaya hai.','team_account',v.id::text);
  return jsonb_build_object('id',v.id,'status','suspended','user_id',v.user_id);
end;
$$;

create or replace function public.jb_team_reactivate_internal(
  p_owner_user_id uuid,p_team_account_id uuid
)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v public.team_accounts%rowtype;
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  select * into v from public.team_accounts where id=p_team_account_id for update;
  if not found then raise exception 'TEAM_ACCOUNT_NOT_FOUND'; end if;
  if v.status<>'suspended' then raise exception 'TEAM_ACCOUNT_NOT_SUSPENDED'; end if;
  if v.user_id is null then raise exception 'TEAM_AUTH_USER_REQUIRED'; end if;

  insert into public.user_roles(user_id,role,created_at,updated_at)
  values(v.user_id,v.assigned_role,now(),now())
  on conflict(user_id) do update set role=excluded.role,updated_at=now();
  if v.assigned_role='reporter'::public.app_role and v.reporter_id is not null then
    update public.reporters set active=true,updated_at=now() where id=v.reporter_id;
  end if;
  update public.team_accounts
  set status='active',last_reactivated_at=now(),suspended_at=null,status_reason=null,updated_at=now()
  where id=v.id;
  perform private.jb_team_history_internal(
    v.id,p_owner_user_id,'team_reactivated','suspended','active',
    v.assigned_role,v.assigned_role,null,jsonb_build_object('live_regrant','NOT_AUTOMATIC')
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_reactivated','team_account',v.id::text,
         jsonb_build_object('assigned_role',v.assigned_role::text,'live_regrant','NOT_AUTOMATIC'));
  insert into public.live_notifications(
    recipient_user_id,notification_type,priority,title,safe_message,record_type,record_id
  ) values(v.user_id,'TEAM_ACCOUNT_REACTIVATED','HIGH','JANTA BOL access reactivated',
           'Aapka newsroom access dobara activate ho gaya hai. Purane Live grants automatically restore nahi hote.',
           'team_account',v.id::text);
  return jsonb_build_object('id',v.id,'status','active','assigned_role',v.assigned_role,'live_regrant','NOT_AUTOMATIC');
end;
$$;

create or replace function public.jb_team_change_role_internal(
  p_owner_user_id uuid,p_team_account_id uuid,p_new_role public.app_role,
  p_reason text default 'ROLE_CHANGED'
)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare
  v public.team_accounts%rowtype; v_old_role public.app_role;
  v_reason text:=left(btrim(coalesce(p_reason,'ROLE_CHANGED')),500);
  v_reporter_id uuid;
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  if p_new_role is null or p_new_role='owner'::public.app_role then raise exception 'OWNER_ROLE_RESERVED'; end if;
  select * into v from public.team_accounts where id=p_team_account_id for update;
  if not found then raise exception 'TEAM_ACCOUNT_NOT_FOUND'; end if;
  if v.status='departed' then raise exception 'TEAM_ACCOUNT_DEPARTED'; end if;
  v_old_role:=v.assigned_role;
  if v_old_role=p_new_role then
    return jsonb_build_object('id',v.id,'status',v.status,'assigned_role',v.assigned_role,'changed',false);
  end if;

  if v.status='active' and v.user_id is not null then
    if v_old_role='reporter'::public.app_role then
      if exists(select 1 from public.user_roles where user_id=v.user_id and role='reporter'::public.app_role) then
        perform public.jb_live_suspend_reporter_internal(p_owner_user_id,v.user_id,'TEAM_ROLE_CHANGED');
        perform public.jb_live_revoke_reporter_capabilities_internal(p_owner_user_id,v.user_id,'TEAM_ROLE_CHANGED');
      end if;
    else
      delete from auth.sessions where user_id=v.user_id;
    end if;
    insert into public.user_roles(user_id,role,created_at,updated_at)
    values(v.user_id,p_new_role,now(),now())
    on conflict(user_id) do update set role=excluded.role,updated_at=now();

    if p_new_role='reporter'::public.app_role then
      select id into v_reporter_id from public.reporters where user_id=v.user_id;
      if v_reporter_id is null then
        insert into public.reporters(
          user_id,name,contact,active,live_permission,public_name_enabled,created_at,updated_at
        ) values(v.user_id,v.display_name,v.contact,true,false,true,now(),now())
        returning id into v_reporter_id;
      else
        update public.reporters set active=true,updated_at=now() where id=v_reporter_id;
      end if;
      update public.team_accounts set reporter_id=v_reporter_id where id=v.id;
    elsif v.reporter_id is not null then
      update public.reporters set active=false,updated_at=now() where id=v.reporter_id;
    end if;
  end if;

  update public.team_accounts set assigned_role=p_new_role,updated_at=now() where id=v.id;
  perform private.jb_team_history_internal(
    v.id,p_owner_user_id,'team_role_changed',v.status,v.status,
    v_old_role,p_new_role,v_reason,'{}'::jsonb
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_role_changed','team_account',v.id::text,
         jsonb_build_object('old_role',v_old_role::text,'new_role',p_new_role::text,'reason',v_reason));
  return jsonb_build_object('id',v.id,'status',v.status,'old_role',v_old_role,'assigned_role',p_new_role,'changed',true);
end;
$$;

create or replace function public.jb_team_set_public_name_internal(
  p_owner_user_id uuid,p_team_account_id uuid,p_enabled boolean
)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v public.team_accounts%rowtype;
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  select * into v from public.team_accounts where id=p_team_account_id for update;
  if not found then raise exception 'TEAM_ACCOUNT_NOT_FOUND'; end if;
  if v.reporter_id is null then raise exception 'REPORTER_PROFILE_REQUIRED'; end if;
  update public.reporters set public_name_enabled=coalesce(p_enabled,false),updated_at=now()
  where id=v.reporter_id;
  perform private.jb_team_history_internal(
    v.id,p_owner_user_id,'team_public_name_changed',v.status,v.status,
    v.assigned_role,v.assigned_role,null,
    jsonb_build_object('public_name_enabled',coalesce(p_enabled,false))
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_public_name_changed','team_account',v.id::text,
         jsonb_build_object('public_name_enabled',coalesce(p_enabled,false)));
  return jsonb_build_object('id',v.id,'public_name_enabled',coalesce(p_enabled,false));
end;
$$;

create or replace function public.jb_team_depart_internal(
  p_owner_user_id uuid,p_team_account_id uuid,p_reason text
)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v public.team_accounts%rowtype;
  v_reason text:=nullif(left(btrim(coalesce(p_reason,'')),500),'');
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  if v_reason is null then raise exception 'REASON_REQUIRED'; end if;
  select * into v from public.team_accounts where id=p_team_account_id for update;
  if not found then raise exception 'TEAM_ACCOUNT_NOT_FOUND'; end if;
  if v.status='departed' then raise exception 'TEAM_ACCOUNT_ALREADY_DEPARTED'; end if;

  if v.user_id is not null then
    if v.status='active' and v.assigned_role='reporter'::public.app_role
       and exists(select 1 from public.user_roles where user_id=v.user_id and role='reporter'::public.app_role) then
      perform public.jb_live_suspend_reporter_internal(p_owner_user_id,v.user_id,v_reason);
      perform public.jb_live_revoke_reporter_capabilities_internal(p_owner_user_id,v.user_id,v_reason);
    else
      delete from auth.sessions where user_id=v.user_id;
    end if;
    delete from public.user_roles where user_id=v.user_id and role<>'owner'::public.app_role;
  end if;
  if v.reporter_id is not null then
    update public.reporters set active=false,updated_at=now() where id=v.reporter_id;
  end if;
  update public.team_accounts
  set status='departed',departed_at=now(),status_reason=v_reason,updated_at=now()
  where id=v.id;
  perform private.jb_team_history_internal(
    v.id,p_owner_user_id,'team_departed',v.status,'departed',
    v.assigned_role,v.assigned_role,v_reason,'{}'::jsonb
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_departed','team_account',v.id::text,
         jsonb_build_object('reason',v_reason,'assigned_role',v.assigned_role::text));
  return jsonb_build_object('id',v.id,'status','departed');
end;
$$;

create or replace function public.jb_team_revoke_session_internal(
  p_owner_user_id uuid,p_team_account_id uuid,p_session_id uuid,
  p_reason text default 'LOST_DEVICE'
)
returns boolean language plpgsql security definer set search_path=''
as $$
declare v_user uuid; v_count int:=0;
  v_reason text:=left(btrim(coalesce(p_reason,'LOST_DEVICE')),500);
begin
  if not exists(select 1 from public.user_roles where user_id=p_owner_user_id and role='owner'::public.app_role)
    then raise exception 'OWNER_REQUIRED'; end if;
  select user_id into v_user from public.team_accounts where id=p_team_account_id;
  if v_user is null then raise exception 'TEAM_AUTH_USER_REQUIRED'; end if;
  delete from auth.sessions where id=p_session_id and user_id=v_user;
  get diagnostics v_count=row_count;
  if v_count<>1 then raise exception 'TEAM_SESSION_NOT_FOUND'; end if;
  perform private.jb_team_history_internal(
    p_team_account_id,p_owner_user_id,'team_session_revoked',null,null,null,null,v_reason,
    jsonb_build_object('session_id',p_session_id)
  );
  insert into public.audit_logs(actor_user_id,action,record_type,record_id,metadata)
  values(p_owner_user_id,'team_session_revoked','team_account',p_team_account_id::text,
         jsonb_build_object('reason',v_reason,'session_id',p_session_id));
  return true;
end;
$$;

-- Initial browser wrappers. A later B1 hardening migration moves all Team
-- browser authority behind jb-team-api to preserve the Phase-3 T123 boundary.
create or replace function public.jb_team_activate(p_team_account_id uuid)
returns jsonb language plpgsql security definer set search_path=''
as $$ begin
  if not private.current_owner_recent_mfa(600) then raise exception 'OWNER_RECENT_MFA_REQUIRED'; end if;
  return public.jb_team_activate_internal(auth.uid(),p_team_account_id);
end; $$;

create or replace function public.jb_team_suspend(p_team_account_id uuid,p_reason text)
returns jsonb language plpgsql security definer set search_path=''
as $$ begin
  if not private.current_owner_recent_mfa(600) then raise exception 'OWNER_RECENT_MFA_REQUIRED'; end if;
  return public.jb_team_suspend_internal(auth.uid(),p_team_account_id,p_reason);
end; $$;

create or replace function public.jb_team_reactivate(p_team_account_id uuid)
returns jsonb language plpgsql security definer set search_path=''
as $$ begin
  if not private.current_owner_recent_mfa(600) then raise exception 'OWNER_RECENT_MFA_REQUIRED'; end if;
  return public.jb_team_reactivate_internal(auth.uid(),p_team_account_id);
end; $$;

create or replace function public.jb_team_change_role(
  p_team_account_id uuid,p_new_role public.app_role,p_reason text default 'ROLE_CHANGED'
)
returns jsonb language plpgsql security definer set search_path=''
as $$ begin
  if not private.current_owner_recent_mfa(600) then raise exception 'OWNER_RECENT_MFA_REQUIRED'; end if;
  return public.jb_team_change_role_internal(auth.uid(),p_team_account_id,p_new_role,p_reason);
end; $$;

create or replace function public.jb_team_set_public_name(p_team_account_id uuid,p_enabled boolean)
returns jsonb language plpgsql security definer set search_path=''
as $$ begin
  if not private.current_owner_recent_mfa(600) then raise exception 'OWNER_RECENT_MFA_REQUIRED'; end if;
  return public.jb_team_set_public_name_internal(auth.uid(),p_team_account_id,p_enabled);
end; $$;

create or replace function public.jb_team_depart(p_team_account_id uuid,p_reason text)
returns jsonb language plpgsql security definer set search_path=''
as $$ begin
  if not private.current_owner_recent_mfa(600) then raise exception 'OWNER_RECENT_MFA_REQUIRED'; end if;
  return public.jb_team_depart_internal(auth.uid(),p_team_account_id,p_reason);
end; $$;

create or replace function public.jb_team_list_sessions(p_team_account_id uuid)
returns table(session_id uuid,created_at timestamptz,updated_at timestamptz,
  refreshed_at timestamp,aal text,user_agent text,ip text)
language plpgsql security definer set search_path=''
as $$
declare v_user uuid;
begin
  if not private.current_owner_aal2() then raise exception 'OWNER_AAL2_REQUIRED'; end if;
  select user_id into v_user from public.team_accounts where id=p_team_account_id;
  if v_user is null then return; end if;
  return query
  select s.id,s.created_at,s.updated_at,s.refreshed_at,s.aal::text,s.user_agent,s.ip::text
  from auth.sessions s where s.user_id=v_user
  order by coalesce(s.refreshed_at,s.updated_at::timestamp) desc;
end;
$$;

create or replace function public.jb_team_revoke_session(
  p_team_account_id uuid,p_session_id uuid,p_reason text default 'LOST_DEVICE'
)
returns boolean language plpgsql security definer set search_path=''
as $$ begin
  if not private.current_owner_recent_mfa(600) then raise exception 'OWNER_RECENT_MFA_REQUIRED'; end if;
  return public.jb_team_revoke_session_internal(auth.uid(),p_team_account_id,p_session_id,p_reason);
end; $$;

create or replace function public.jb_team_list()
returns table(
  team_account_id uuid,user_id uuid,reporter_id uuid,display_name text,contact text,
  invite_email text,assigned_role text,status text,public_name_enabled boolean,
  reporter_active boolean,live_permission boolean,invited_at timestamptz,
  activated_at timestamptz,suspended_at timestamptz,departed_at timestamptz,updated_at timestamptz
)
language plpgsql security definer set search_path=''
as $$
begin
  if not private.current_owner_aal2() then raise exception 'OWNER_AAL2_REQUIRED'; end if;
  return query
  select ta.id,ta.user_id,ta.reporter_id,ta.display_name,ta.contact,ta.invite_email,
         ta.assigned_role::text,ta.status,coalesce(r.public_name_enabled,false),
         coalesce(r.active,false),coalesce(r.live_permission,false),
         ta.invited_at,ta.activated_at,ta.suspended_at,ta.departed_at,ta.updated_at
  from public.team_accounts ta left join public.reporters r on r.id=ta.reporter_id
  order by case ta.status when 'pending' then 0 when 'active' then 1 when 'suspended' then 2 else 3 end,
           ta.updated_at desc;
end;
$$;

create or replace function public.jb_team_history(p_team_account_id uuid)
returns table(history_id bigint,action text,old_status text,new_status text,old_role text,
  new_role text,reason text,metadata jsonb,created_at timestamptz)
language plpgsql security definer set search_path=''
as $$
begin
  if not private.current_owner_aal2() then raise exception 'OWNER_AAL2_REQUIRED'; end if;
  return query
  select h.id,h.action,h.old_status,h.new_status,h.old_role::text,h.new_role::text,
         h.reason,h.metadata,h.created_at
  from public.team_account_history h
  where h.team_account_id=p_team_account_id
  order by h.created_at desc,h.id desc;
end;
$$;

create or replace function public.jb_public_reporter_directory()
returns table(reporter_id uuid,display_name text)
language sql stable security definer set search_path=''
as $$
  select r.id,r.name
  from public.reporters r join public.team_accounts ta on ta.reporter_id=r.id
  where r.public_name_enabled=true and ta.status in('active','departed')
  order by lower(r.name),r.id;
$$;

revoke all on function private.jb_team_history_internal(uuid,uuid,text,text,text,public.app_role,public.app_role,text,jsonb) from public;
revoke all on function public.jb_team_create_pending_internal(uuid,uuid,text,text,public.app_role,text) from public,anon,authenticated;
revoke all on function public.jb_team_activate_internal(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jb_team_suspend_internal(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.jb_team_reactivate_internal(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jb_team_change_role_internal(uuid,uuid,public.app_role,text) from public,anon,authenticated;
revoke all on function public.jb_team_set_public_name_internal(uuid,uuid,boolean) from public,anon,authenticated;
revoke all on function public.jb_team_depart_internal(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.jb_team_revoke_session_internal(uuid,uuid,uuid,text) from public,anon,authenticated;

grant execute on function public.jb_team_create_pending_internal(uuid,uuid,text,text,public.app_role,text) to service_role;
grant execute on function public.jb_team_activate_internal(uuid,uuid) to service_role;
grant execute on function public.jb_team_suspend_internal(uuid,uuid,text) to service_role;
grant execute on function public.jb_team_reactivate_internal(uuid,uuid) to service_role;
grant execute on function public.jb_team_change_role_internal(uuid,uuid,public.app_role,text) to service_role;
grant execute on function public.jb_team_set_public_name_internal(uuid,uuid,boolean) to service_role;
grant execute on function public.jb_team_depart_internal(uuid,uuid,text) to service_role;
grant execute on function public.jb_team_revoke_session_internal(uuid,uuid,uuid,text) to service_role;

revoke all on function public.jb_team_activate(uuid) from public,anon;
revoke all on function public.jb_team_suspend(uuid,text) from public,anon;
revoke all on function public.jb_team_reactivate(uuid) from public,anon;
revoke all on function public.jb_team_change_role(uuid,public.app_role,text) from public,anon;
revoke all on function public.jb_team_set_public_name(uuid,boolean) from public,anon;
revoke all on function public.jb_team_depart(uuid,text) from public,anon;
revoke all on function public.jb_team_list_sessions(uuid) from public,anon;
revoke all on function public.jb_team_revoke_session(uuid,uuid,text) from public,anon;
revoke all on function public.jb_team_list() from public,anon;
revoke all on function public.jb_team_history(uuid) from public,anon;

grant execute on function public.jb_team_activate(uuid) to authenticated;
grant execute on function public.jb_team_suspend(uuid,text) to authenticated;
grant execute on function public.jb_team_reactivate(uuid) to authenticated;
grant execute on function public.jb_team_change_role(uuid,public.app_role,text) to authenticated;
grant execute on function public.jb_team_set_public_name(uuid,boolean) to authenticated;
grant execute on function public.jb_team_depart(uuid,text) to authenticated;
grant execute on function public.jb_team_list_sessions(uuid) to authenticated;
grant execute on function public.jb_team_revoke_session(uuid,uuid,text) to authenticated;
grant execute on function public.jb_team_list() to authenticated;
grant execute on function public.jb_team_history(uuid) to authenticated;

revoke all on function public.jb_public_reporter_directory() from public;
grant execute on function public.jb_public_reporter_directory() to anon,authenticated;
